name: VMComputers
version: '${version}'
main: com.acclash.vmcomputers.VMComputers
api-version: '1.20'
authors: [ Anston_Sorensen ]
description: Control virtual machines inside of vanilla Minecraft
website: www.acclash.com