name: ProjectMagisha
version: '${project.version}'
main: com.acclash.projectmagisha.ProjectMagisha
api-version: 1.13
authors: [ Anston_Sorensen ]
description: A classified project.
website: www.acclash.com
commands:
  computer:
    description: Manages various actions with computers.
  testmap:
    description: Test the Magisha map.
  givetestmap:
    description: Get the Magisha map.
  magisha:
    description: A classified command.
  armstest:
    description: Poo
  darpatrain:
    description: Delivers you a new experimental DARPA train.
  serialize:
    description: Serializes the current held item and writes it in the Classified yml file.
  deserialize:
    description: Deserializes the last item in the Classified yml file.
  lightpo:
    description: Test the light update
  summonpo:
    description: Summon Po!
  fallingblocktest:
    description: Test the mysterious falling block
  control:
    description: Control an entity!