name: Release Caller

on:
  push:
  pull_request:

jobs:
  call-workflow:
    permissions:
        contents: write
    uses: ac-clash/workflows/.github/workflows/release-called.yml@reusable-workflow
    secrets:
      token: ${{ secrets.TOKEN }}
